name: Release

on:
  workflow_dispatch:
    inputs:
      extra_arguments:
        description: 'Enter release flag'
        required: false
        default: ''
      registry:
        description: 'Enter Registry(optional)'
        default: "https://registry.npmjs.org/"
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    # env:
    #     NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}} 
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup node environment
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org/'
          # Defaults to the user or organization that owns the workflow file
          scope: '@i18n-components'
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}} 
      - run: npm whoami
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - run: yarn
      - run: yarn build

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup node environment
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org/'
          # Defaults to the user or organization that owns the workflow file
          scope: '@i18n-components' 
      - run: yarn
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v2.7.4
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CODE_CLIMATE_REPORTER_ID}}
        with:
          coverageCommand: yarn test
          coverageLocations: |
            ${{github.workspace}}/coverage/lcov.info:lcov
      
  release-package:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # pulls all commits (needed for lerna / semantic release to correctly version)
          fetch-depth: "0"

        # pulls all tags (needed for lerna / semantic release to correctly version)
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - name: Configure CI Git User
        run: |
          git config --global user.name '@apurvaojas'
          git config --global user.email 'apurvaojas@users.noreply.github.com'
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org/'
          # Defaults to the user or organization that owns the workflow file
          scope: '@i18n-components'
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - run: yarn
      - run: yarn release --registry=${{github.event.inputs.registry}} ${{github.event.inputs.extra_arguments}}
        env:
          GH_TOKEN: ${{ github.token }}
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
